/*
 * ROOT macro to display histograms generated by the test programs
 *
 */

void displayCUDAHisto(const char* fileName="../output/reference_CUDA.root")
{
    displayHisto(fileName, "galgal");
}


void displayCPUHisto(const char* fileName="../output/reference_CPU.root")
{
    displayHisto(fileName, "galgal");
}


void displayHisto(const char* fileName, const char* histoName)
{
    TFile* f = TFile::Open(fileName);
    if (f != 0) {
        TH1F* histo = (TH1F*)f->Get(histoName);
        histo->Draw();
    }
}

